spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devconnect
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
